config/routes.rb
  Rails.application.routes.draw do
  devise_for :users
    root "articles#index"

    resources :articles do
      resources :comments
    end
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible
  belongs_to :author, class_name: 'User'
  has_one_attached :image
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }

  scope :ordered, -> (direction = :desc) { order(created_at: direction)}
  scope :with_authors, -> {includes(:author)}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :author, class_name: 'User'
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable :rememberable,
  devise :database_authenticatable, :registerable,
         :recoverable,  :validatable
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referer || root_path)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :set_article, only: %i[show edit update destroy]
  # before_action :authorize_user!, only: %i[edit update destroy]

  def index
    @articles = Article.ordered.with_authors.paginate(page: params[:page], per_page: 2).where('title LIKE ?', "#{params[:search]}%")
    #@articles = Article.all
  end

  def show

  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    @article.author = current_user
    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    authorize @article
  end

  def update
    authorize @article

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    authorize @article

    @article.destroy

    redirect_to root_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :status, :image)
  end

  def set_article
    @article = Article.find(params[:id])
  end

  # def authorize_user!
  #   return if @article.author_id == current_user.id
  #
  #   redirect_to :articles,
  #               alert: "You are not allowed to perform this acrion"
  # end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]

  def create
    @article = Article.find(params[:article_id])
    # params[:comment][:commenter] = current_user.username
    @comment = @article.comments.create(params[:comment].permit(:body).merge(author_id: current_user.id))
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    authorize @comment
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  # def comment_params
  #   params.require(:comment).permit(:commenter, :body, :status)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :image %><br>
    <%= form.file_field :image %><br>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<p class="text-center m-3">Our blog has <%= Article.public_count %> articles and counting!  <%= link_to "New Article", new_article_path %></p>
  <% @articles.each do |article| %>
    <% unless article.archived? %>
      <div style="width: 50%; background-color: rgba(255,255,255,0.2)" class="m-auto p-5 mb-5 rounded">
        <h1 class="mb-3"><%= link_to article.title, article %></h1>
        <% if article.image.attached? %>
        <%= image_tag(article.image, style: 'width:100%; height:auto; margin: auto; display: block',  class: 'mb-3')%>
        <% end %>
        <p class="h4"><%= article.body %>></p>
      </div>
    <% end %>
  <% end %>
<!--<ul>-->
<!--  <li>-->
    <%#= link_to article.title, article %>
<!--  </li>-->
<!--</ul>-->
<div class="text-center mb-5">
  <div class="pagination_links">
    <%= will_paginate @articles, :container => false %>
  </div>
</div>

<!--<div class="text-center"><%#= will_paginate @articles %></div>-->

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<div style="width: 50%; background-color: rgba(255,255,255,0.2)" class="m-auto p-5 my-3 rounded">
  <h1 class="mb-3"><%= @article.title%></h1>
  <% if @article.image.attached? %>
    <%= image_tag(@article.image, style: 'width:100%; height:auto; margin: auto; display: block',  class: 'mb-3')%>
  <% end %>
  <p class="h4"><%= @article.body %>></p>
  <h3 class="mt-3">
    <strong>Author:</strong>
    <%= @article.author.username %>
  </h3>
  <p><% if policy(@article).update? %>
    <%= link_to "Edit", edit_article_path(@article) %> |
  <% end %>
  <% if policy(@article).destroy? %>
    <%= link_to "Destroy", article_path(@article),
                    method: :delete,
                    data: { confirm: "Are you sure?" } %>
  <% end %>
  </p>
</div>
<div style="width: 50%; background-color: rgba(255,255,255,0.2)" class="m-auto p-5 my-3 rounded">
<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.author.username %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<% if policy(comment).destroy? %>
<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
              method: :delete,
              data: { confirm: "Are you sure?" } %>
</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
<!--  <p>-->
<!--    <%#= form.label :commenter %><br>-->
    <%#= form.text_field :commenter %>
<!--  </p>-->
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<!--  <p>-->
<!--    <%#= form.label :status %><br>-->
    <%#= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
<!--  </p>-->
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OrangeBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style=" background-color: #0b0b0b; color: white">
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #2a2a2a;">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">
        <%= image_tag '/images/logo.png', style: 'height:40px;width:auto;'%>
        <strong>OrangeBlog</strong>
      </a>
<!--      <form class="d-flex">-->
<!--        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">-->
<!--        <button class="btn btn-outline-warning" type="submit">Search</button>-->
<!--      </form>-->
      <div class="collapse navbar-collapse justify-content-end " id="navbarNav">
        <ul class="navbar-nav pe-2">
          <%if user_signed_in? %>
            <li class="nav-item"><a class="nav-link disabled text-white" href="#"><%= current_user.email %></a></li>
            <li class="nav-item"><%= link_to 'Log out', destroy_user_session_path, method: :delete, data: {confirm: 'Are you sure ?'}, class: 'nav-link' %></li>
          <% else %>
            <%= link_to 'Log in', new_user_session_path, class: 'nav-link'  %>
          <% end %>
        </ul>
      </div>

      <%= form_tag(articles_path, method: :get, class: 'd-flex') do %>
        <%= text_field_tag(:search, params[:search], class: 'form-control me-2', placeholder: 'Search') %>
        <%= submit_tag("Search", class: 'btn btn-outline-warning') %>
      <% end %>
    </div>
  </nav>
    <%#if user_signed_in? %>
      <%#= current_user.email %>
      <%#= link_to 'Log out', destroy_user_session_path, method: :delete, data: {confirm: 'Are you sure ?'} %>
    <%# else %>
      <%#= link_to 'Log in', new_user_session_path %>
    <%# end %>
  <p class="notice m-0 p-0 text-center"><%= notice %></p>
  <p class="alert m-0 p-0  text-center"><%= alert %></p>

  <%= yield %>
  </body>
</html>